package com.antra.report.client.pojo.type;

public enum ReportStatus {
    GENERATE_PENDING, GENERATED, GENERATE_FAILED, UPDATE_PENDING, UPDATED, UPDATE_FAILED, DELETE_PENDING, DELETED, DELETE_FAILED
}
